module de.vsy.chat.shared_module{
    exports de.vsy.chat.shared_module.packet_creation;
    exports de.vsy.chat.shared_module.packet_exception.handler;
    exports de.vsy.chat.shared_module.packet_exception;
    exports de.vsy.chat.shared_module.packet_management;
    exports de.vsy.chat.shared_module.data_element_validation;
    exports de.vsy.chat.shared_module.packet_processing;
    exports de.vsy.chat.shared_module.exception_processing;
    exports de.vsy.chat.shared_module.packet_processing.processor_provision;
    exports de.vsy.chat.shared_module.packet_validation.content_validation.error;
    exports de.vsy.chat.shared_module.packet_validation.content_validation.chat;
    exports de.vsy.chat.shared_module.packet_validation;
    exports de.vsy.chat.shared_module.packet_transmission;
    exports de.vsy.chat.shared_module.packet_validation.content_validation;
    exports de.vsy.chat.shared_module.packet_validation.content_validation.authentication;
    exports de.vsy.chat.shared_module.packet_validation.content_validation.relation;
    exports de.vsy.chat.shared_module.packet_validation.content_validation.status;
    exports de.vsy.chat.shared_module.packet_creation.identification_provider;
    exports de.vsy.chat.shared_module.packet_transmission.cache;
    exports de.vsy.chat.shared_module.thread_manipulation;
    requires de.vsy.chat.shared_utility;
    requires de.vsy.chat.shared_transmission;
    requires org.apache.logging.log4j;
}